<?php

/**
 * @file
 * Contains module logic for trajenta link generator.
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Database\Database;

/**
 * Implements hook_form_alter() for Link generator webform.
 */
function trajenta_link_generator_form_alter(&$form, $form_state, $form_id){
     if ($form_id == 'webform_submission_trajenta_link_generator_add_form') {
        // $form['#attached']['library'][] = 'trajenta_link_generator/trajenta_js';
         $form['actions']['submit']['#validate'][] = 'trajenta_link_submit';
     }
}

/**
 * Implements Submit handler for Trajenta_link_generator webform.
 */
function trajenta_link_submit($form, FormStateInterface $form_state) {
        $baseUrl = \Drupal::request()->getSchemeAndHttpHost();

        //Fetch all the submitted form values.
        $repId =  $form_state->getValue('rep_id');
        $repEmail =  $form_state->getValue('rep_email');
        $doctorName =  $form_state->getValue('doctor_name');
        $doctorEmail =  $form_state->getValue('doctor_email');
        $veevaId =  $form_state->getValue('doctor_veeva_id');
        $destLink =  $form_state->getValue('destination_link');
        $campaignCid =  $form_state->getValue('campaign_id_cid');
        $cvmSeg =  $form_state->getValue('doctor_cvm_segmentation');

        if (!empty($destLink)) {
        $destLink = implode('', $destLink); 
       }
        //Store in db
        if (!empty($veevaId) && !empty($destLink)) {
       
        $conn = Database::getConnection();
        $conn->insert('trajentalink')->fields(
        array(
        'veevaid' => $veevaId,
        'destination' => $destLink,
            )
        )->execute();
        }
        //check if the deeplink required radio button field is yes or no.
        //If yes, generate deeplink url else generate external url.
    if ($form_state->getValue('deeplink_required') == 'Yes') {

        $external = $baseUrl. '/' .$veevaId ;
        $form_state->setValue('deeplink', $external);
        $finalLink = $form_state->getValue('deeplink');
        \Drupal::service('messenger')->addMessage($finalLink);

        } else {

        $result = $repId . "" . $doctorName . "" . $campaignCid;
        $result = str_shuffle(substr($result, 0, 7));
        $external = $baseUrl . '/' . $result;

        $form_state->setValue('deeplink', $external);
        $finalLink = $form_state->getValue('deeplink');
       \Drupal::service('messenger')->addMessage($finalLink);

        }
}

